GEMINI_API_KEY = "AIzaSyCP-sMnv98TkFRhRMrj2CGPzoNyXSY5wpk"

OPENAI_API_KEY = "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"